"""Add team_id to player_profile

Revision ID: dc2c249db545
Revises: 
Create Date: 2026-05-13 14:01:04.142448

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



revision = 'dc2c249db545'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_profiles', sa.Column('team_id', sa.Integer(), nullable=True))
    with op.batch_alter_table('player_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_profiles_team_id'), ['team_id'], unique=False)
        batch_op.create_foreign_key('fk_player_profiles_teams', 'teams', ['team_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_profiles', schema=None) as batch_op:
        batch_op.drop_constraint('fk_player_profiles_teams', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_player_profiles_team_id'))
        batch_op.drop_column('team_id')
    # ### end Alembic commands ###
